### ISSUE TITLE
Create the mobile and tablet menu

### ISSUE THREAD

**Issue by arkatsy** [arkatsy/zals-ecommerce#21]
The next part now is the overlay menu.

Some notes for the menu.

The animation will be from right to the left and for transitions we can go with ease out and ease in.

Now for mobile screens, the overlay will cover the full screen.

For more wide screens but not larger than `lg` ( you can see when the hamburger icon disappears ), I'm thinking that it may be 
a weird looking to cover the full screen. On these sizes we should make it to cover maybe the 80% of the screen, something like this. We can go with what feels nice. 

One last important thing to not forget is we will need to listen for click events outside of the overlay so when the user tap outside of it ( on tablet let's say) the overlay will close.

On the end of this task we should have at least a basic functional overlay menu that closes and opens and you can navigate to subcategories.

**Comment by andrijantasevski** [comment]
I think that we should use headlessUI for implementing this. It's very messy to try implementing an accessible modal/popover. I've tried it out a couple of times, but we'd have to use many refs and add tons of event listeners. 

Take a look at how dialogs are implemented in headlessUI.

https://headlessui.com/react/dialog

Radix primitives are also an alternatives to this.

Sure, we can try to implement it from scratch if you want, but I'd advise against it because we can never get it to be that perfect.

**Comment by vercyle** [comment]
Let's go with headless ui since I've used it before, it'll be familiar for me too. 

Implementing our own will take also additional time. Let's avoid that better
